# here we're giving it a name to our  pipeline
name: CI workflow

# we also need to specify some workflow triggers,
# which define when we're launching the pipeline
on:
  # in this case, every time there is a push...
  push:
    # on the main branch
    branches: ["main"]
  # or a pull request
  pull_request:
    # to the main branch as well, 
    branches: ["main"]

# we'll run the...
jobs:
  # build job
  build:
    # on the ubuntu-latest runner
    runs-on: ubuntu-latest
    # using a python docker image.
    container: python:3.9-slim
    # This job will have the following steps:
    steps:
      # checkout step, 
      - name: Checkout
        # It will use the checkout template by GitHub actions.
        uses: actions/checkout@v3
      # Dependency installation step, 
      - name: Install dependencies
        # that will upgrade packages and install the dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Lint the code using flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

